#!/bin/bash
set -e
[ ! -z "$OPENAI_API_KEY" ]
if [ "$#" -eq 0 ]; then
	TMP=$(mktemp)
	trap 'rm -f "$TMP"' EXIT INT TERM HUP
	${EDITOR:-ed} $TMP
	[ ! -s "$TMP" ] && exit
	MSG=$(cat $TMP)
else
	MSG="$*"
fi
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d "{
    \"model\": \"gpt-4.1-mini\",
    \"messages\": [
      {\"role\": \"user\", \"content\": \"$MSG\"}
    ]
  }" 2>/dev/null | jq '.choices.[0].message.content'
