#!/bin/bash
set -e
[ ! -z "$OPENAI_API_KEY" ]
MSG=${@}
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d "{
    \"model\": \"gpt-4.1-mini\",
    \"messages\": [
      {\"role\": \"user\", \"content\": \"$MSG\"}
    ]
  }" 2>/dev/null | jq '.choices.[0].message.content'
